### ISSUE TITLE
Not working when using fork

### ISSUE THREAD

**Issue by leesiongchan** [ilearnio/module-alias#1]
package.json
```javascript
{
  ...
  "dependencies": {
    ...
    "react-helmet": "moviepilot/react-helmet",
    ...
  }
  ...
}
```

```javascript
module.js:340
    throw err;
    ^

Error: Cannot find module 'react-helmet'
...
```

**Comment by ilearnio** [comment]
It seems there is something wrong with the module you're trying to `require`. It's `package.json` contains a line `"main": "./lib/index.js",`. There is no such file, so it causes the error

**Comment by ilearnio** [comment]
Anyway I have added a test case to make sure it is working when requiring repos
