### ISSUE TITLE
Using it with babel

### ISSUE THREAD

**Issue by Devric** [ilearnio/module-alias#2]
Any chance this works with babel-cli?

i basically converts to es5 from babel-cli than run normal node server on the compiled code.

**Comment by ilearnio** [comment]
Have you tried to set up module-alias programmatically, or you just use package.json as a place to store aliases? I'm not sure whether babel-cli uses some custom way to `require` modules but if not then the setup should be pretty much the same

**Comment by Devric** [comment]
tried both aint working, babel seems to have resolve config similar to webpack. i'll see if it shares similar mechanism

**Comment by ilearnio** [comment]
I guess it shoud be fixed now. Is there any way you could check it again?

**Comment by ilearnio** [comment]
I'm closing this since no response

**Comment by ndabAP** [comment]
I still got the issue. When I transpile it with babel into another directory the require statement aims to my untranspiled code.

**src/index.js**
```js
import a from '@b'
```

This resolves to `src/` instead of `dist/src`:

**dist/src/index**
```js
var a = require('@b')
```

**Comment by ilearnio** [comment]
@ndabAP You need to configure your aliases relative to the directory, like `moduleAlias.addAlias('@b', __dirname + '/b')` so it will look deeper in the current directory only
