### ISSUE TITLE
Module._resolveFilename override does nothing

### ISSUE THREAD

**Issue by vjpr** [ilearnio/module-alias#3]
I mayb be missing something, but I implemented this in my code, and checked the logic and it appears that it is not passing on the modified request.

```js
var oldResolveFilename = Module._resolveFilename
Module._resolveFilename = function (request, self) {
  for (var alias in moduleAliases) {
    if (request.indexOf(alias) === 0) {
      request = nodePath.join(
        moduleAliases[alias],
        request.substr(alias.length)
      )
    }
  }

  return oldResolveFilename.apply(this, arguments)
}
```

I think it needs to be:

```js
Module._resolveFilename = function (request, parent, isMain) {

...

return oldResolveFilename.call(this, request, parent, isMain)
```

**Comment by ilearnio** [comment]
I just ran tests on latest Node v6.2.1 and it passed. Have you looked into some simple examples from tests like this one https://github.com/ilearnio/module-alias/blob/master/test/specs.js#L24-L33? Does your code look similar?

**Comment by vjpr** [comment]
@ilearnio So your code is fine, and I learned about another strange quirk of JS today :)

I assumed that when primitives passed to a function, they simply became local copies. But it turns out that in non-strict mode (and some other situations) they share values with the `arguments` object.

And it turns out that when compiling my code with Babel, by default it uses strict mode (placing `'use strict;` at the top of each file).

So my suggestion would be to explicitly pass through the parameters to avoid breakages if used in strict-mode. But the chance of this causing issues is probably quite low unless someone concatenates Node.js or transpiles the source at a later time...

From [ES5 clause 10.6 (note 1)](http://ecma262-5.com/ELS5_HTML.htm#Section_10.6):

> For non-strict mode functions the array index (defined in 15.4) **named data properties of an arguments object** whose numeric name values are less than the number of formal parameters of the corresponding function object initially **share their values with the corresponding argument bindings in the function’s execution context**. This means that **changing the property changes the corresponding value of the argument binding and vice-versa**. This correspondence is broken if such a property is deleted and then redefined or if the property is changed into an accessor property. **For strict mode functions, the values of the arguments object‘s properties are simply a copy of the arguments passed to the function and there is no dynamic linkage between the property values and the formal parameter values.**

**Comment by ilearnio** [comment]
@vjpr That's a good catch! You are right. When I added `'use strict'` at the top of the file some everything got broken. Fixed it as you suggested. Thanks!
