### ISSUE TITLE
Does not work with `fs`

### ISSUE THREAD

**Issue by Sawtaytoes** [ilearnio/module-alias#30]
```json
  "_moduleAliases": {
    "$utils": "./utils"
  },
```

```js
require('module-alias')
const fs = require('fs')

console.log(
	fs.existsSync('$utils/fun.js')
)
```

When I am making calls with `fs`, none of the aliases are working for me. Is that normal?

I tried `fs.writeFile` and others as well.

**Comment by ilearnio** [comment]
Correct, it doesn't suppose to. The purpose of this plugin to add aliases support for `require`/`import`  only
