### ISSUE TITLE
Module Alias unable to locate it's own package.json

### ISSUE THREAD

**Issue by Vijendra07Kulhade** [ilearnio/module-alias#38]
I have a directly structure like this.
`/app/project/src/index.js`
I am using `require('module-alias/register')`
I see node_modules created at `/app/node_modules`
but looks like below file is not able to find package.json.
It is right there at `/app/node_modules/module-alias/` but it is looking at `/app/`.
```
    /app/node_modules/module-alias/index.js:155
    throw new Error('Unable to read ' + packagePath)
    
Error: Unable to read /app/package.json
    at init (/app/node_modules/module-alias/index.js:155:11)

**Comment by ilearnio** [comment]
It works as long as you have `package.json` in the same folder as `node_modules`, which contains `module-alias` package

**Comment by ilearnio** [comment]
Alternatively you can do `require('module-alias')(pathToPackageJson)`

**Comment by ragaar** [comment]
Hmm. Which package.json are you referring to?
I've tried all of the following without success:
```
require('module-alias')('../node_modules/module-alias/register')
```

```
require('module-alias')('../node_modules/module-alias/package.json')
```

```
require('module-alias')('../node_modules/module-alias')
```

**Comment by Vijendra07Kulhade** [comment]
@ragaar I was referring to `node_modules/module-alias/package.json`. It was giving me error when I was not explicitly using `moduleAlias.addAliases({})`. When I started doing it, I didn't see the error.

**Comment by ilearnio** [comment]
@ragaar You are doing it wrong. You need to pass your app's package.json, not module-alias'es package.json
