### ISSUE TITLE
Its just not working

### ISSUE THREAD

**Issue by maxmaxmaximus2** [ilearnio/module-alias#39]
![image](https://user-images.githubusercontent.com/40377663/47962766-96ee8200-e032-11e8-8375-be3f4a287405.png)

![image](https://user-images.githubusercontent.com/40377663/47962767-a1a91700-e032-11e8-9e3d-ae4b68c6463a.png)

![image](https://user-images.githubusercontent.com/40377663/47962772-aa99e880-e032-11e8-8c94-1c6a448234be.png)

![image](https://user-images.githubusercontent.com/40377663/47962775-b4bbe700-e032-11e8-8dbb-dd915fddc71b.png)

![image](https://user-images.githubusercontent.com/40377663/47962782-cdc49800-e032-11e8-9ef2-a3724bb001c4.png)

the same effect:
```javascript
"ololo": "./qq.js"
"ololo": "qq.js"
"ololo": "./qq"
"ololo": "qq"
```

even if i create empty node-modules directory, it not working

![image](https://user-images.githubusercontent.com/40377663/47962803-25630380-e033-11e8-9b19-38102258ee0f.png)

it should consider the root directory is not the folder where node_modules is located, but the folder where package.json is located

is not it?

**Comment by maxmaxmaximus2** [comment]
if i add one dependency jquery and run `npm i` in `/build/server/` directory. npm install jquery to `/build/server/node_modules/jquery` directory and create `package-lock.json` file.

![image](https://user-images.githubusercontent.com/40377663/47962856-f7ca8a00-e033-11e8-96df-8c38e157e95d.png)


but your library dont use it `package.json` file in `/build/server` directory. he use `package.json` from my root project directory

**Comment by maxmaxmaximus2** [comment]
SOLUTION
===

if i install `module-alias` to build directory, node engine catch is from local `node_modules` folder.
and all works:

![image](https://user-images.githubusercontent.com/40377663/47966476-eb5e2580-e063-11e8-99ff-1a110a8c7052.png)

**Comment by maxmaxmaximus2** [comment]
Apparently your module uses the `__dirname` property to get the working directory.

**Comment by maxmaxmaximus2** [comment]
use `require.main.filename` to get main index.js file and get to top level to get first `package.json` file

is a 100%  chance =)

**Comment by maxmaxmaximus2** [comment]
![image](https://user-images.githubusercontent.com/40377663/47969179-b31b0f00-e084-11e8-8d2f-710733d9721f.png)

ahahah 

you neet remove this line
```javascript
  var packagePath = base.replace(/\/package\.json$/, '') + '/package.json'
```

and use node path module to resolve paths, cuz i use windows))) and ` + '/package.json'` not correct

**Comment by maxmaxmaximus2** [comment]
i found fix:


![image](https://user-images.githubusercontent.com/40377663/47969373-71d82e80-e087-11e8-9819-3a11294005a0.png)


but ideally, you should check current, and through all the top directories in search of the package.json file

**Comment by ilearnio** [comment]
For the cases when it cannot be found automatically you can always pass a custom path to `moduleAlias(PATH)`, just as you did. By default it only looks for a package.json in a folder one level above `node_modules` (in 99% chances it's the app's root), so it's very trivial
