### ISSUE TITLE
Thanks a lot!

### ISSUE THREAD

**Issue by louisameline** [ilearnio/module-alias#4]
A quick note to thank you for this module, since no one has yet!
This is exactly what I was looking for, really awesome. I can't believe it didn't exist until 3 months ago as similar libraries are not so convincing.

I've seen how the npm is opinionated about not implementing aliases and while I can understand the rationale, I think they are a good addition sometimes. Your lib helps me make paths more consistent between npm and the requirejs front end, which I find really nice. Anyway, thanks again.

**Comment by ilearnio** [comment]
Hey @louisameline, thanks for nice words :) Glad you like it. Yeah, I developed it recently since there was no anything similar to it on npm, which is really strange, and I wanted to have aliases badly in my project.
