### ISSUE TITLE
eslint warnings and IDE intellisense.

### ISSUE THREAD

**Issue by Dzenly** [ilearnio/module-alias#48]
Are there ways how to say eslint, WebStorm, VS Code, about my `@root` so as
eslint will stop warn about unresolved paths, and VSCode autocompletion started to work with such paths started with `@root` and `Go to definition` started to work for such require('@root/bla/bla1').
?

Related to https://github.com/ilearnio/module-alias/issues/19

**Comment by cdichiara** [comment]
Yeah I don't think I'll use this package until the eslint import/no-unresolved warnings are nullified... nice design though. :+1

**Comment by ilearnio** [comment]
Are you using [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import) for linting require/import paths? If so then I think this issue should be discussed in that plugin's repo, since I don't think I can help here

**Comment by ilearnio** [comment]
Perhaps this can help https://www.npmjs.com/package/eslint-import-resolver-alias

**Comment by cdichiara** [comment]
Thanks, I'll go look ... I just assumed there'd be some way that you would register your require() syntax with eslint so that it understood it and was able to verify it. I'll check out the packages you suggested, thanks. :)

**Comment by ilearnio** [comment]
Going to close it since it's not related to module-alias itself

**Comment by blowsie** [comment]
Anyone manage to avoid 
`node/no-missing-require` warnings ?

**Comment by Kehrlann** [comment]
@blowsie nope ... have you tried giving the "allowModules" options for configuring eslint ? It might work.

Reference:
https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-require.md
