### ISSUE TITLE
Problem with Meteor JS!

### ISSUE THREAD

**Issue by thearabbit** [ilearnio/module-alias#5]
I tried, but don't work

``` js
// Client
const moduleAlias = require('module-alias');
moduleAlias.addAlias('@home', './home.js')

import '@home'
```

**Comment by thearabbit** [comment]
It show
```js
index.js:9 Uncaught TypeError: Cannot read property '_nodeModulePaths' of undefined
```

**Comment by ilearnio** [comment]
Apparently Meteor uses it's own `require` implementation since it has no `_nodeModulePaths` property. I don't think I would have time to implement it at least in the near future. Pull requests are welcome

**Comment by thearabbit** [comment]
thanks for your reply, but I don't understand about this to PR.
