### ISSUE TITLE
Preserve IntelliSense

### ISSUE THREAD

**Issue by skatestyle** [ilearnio/module-alias#52]
I have a small, but annoying issue with this package.
By default Visual Studio Code comes with IntelliSense, where you can  type `object.` and you will get a list of all possible functions / params / etc.

But when using path aliases, the IntelliSense isn't working anymore.

**Comment by labs20** [comment]
+1 using Webstorm

**Comment by skatestyle** [comment]
And what if I want to keep using Visual Studio Code?

**Comment by kabamjstell** [comment]
Using tsconfig.json and setting `path` and `baseUrl` should help intellisense with vscode.
`{
    "baseUrl": "./src",
    "paths": {
        "@/*": [ "*" ]
    }
}`

**Comment by ilearnio** [comment]
For autocomplete in JS files try this https://github.com/ilearnio/module-alias/issues/19#issuecomment-395943981 . I think you will need to install a VSCode extension for that config to work

**Comment by divrse** [comment]
@flolu did you get it working using the method @ilearnio suggessted or another way? I wasn't able to.

**Comment by flolu** [comment]
@divrse No I didn't either.
But there is an easier way.

Just use the `paths` attribute in your `tsconfig.json` file. VSCode will automatically recognize it.
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "strict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es5",
    "paths": {
      "@project/*": ["./packages/*"],
      "@othjerProject/*": ["./services/client/*"]
    },
  },
}
```

Let me know if this solved your problem! :)

**Comment by divrse** [comment]
@flolu my project is node rather than typescript , although I've tried the following tsconfig to no avail
```{
  "compilerOptions": {
    "baseUrl": "./",
    "strict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es5",
    "paths": {
      "@project/*": ["./packages/*"],
      "@othjerProject/*": ["./services/client/*"]
    },
  },
}```

**Comment by flolu** [comment]
@divrse Mh.... I'm not sure it will work if you don't use Typescript

**Comment by divrse** [comment]
@flolu yea I'd imagine it only works for .ts files

Thanks for the suggestion, maybe I'll stumble upon something.

I've also tried link-module-alias but it isn't a viable solution because it has an issue of deleting your source code if you use @ prefix.

Another thing I came across was using the following jsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "commonjs",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```
which didn't work for object completion.
Thanks for the quick response.

@ilearnio Now that it's been a year later do you know anything you could reccomend?

**Comment by flolu** [comment]
@divrse Good luck with it!
I'd recommend using Typescript :rofl:
