### ISSUE TITLE
Breaks `require.resolve`

### ISSUE THREAD

**Issue by mikew** [ilearnio/module-alias#53]
Looks like `_resolveFilename` actually takes 4 arguments:

```
> m._resolveFilename.toString()
'function(request, parent, isMain, options) ...'
```

Without passing that options argument, `require.resolve(something, { paths: [] })` breaks.

I've made a sample repository here: https://github.com/mikew/module-alias-issue

**Comment by Kehrlann** [comment]
Fixed by #64
