### ISSUE TITLE
VSCode resolution failing for "excluded" files

### ISSUE THREAD

**Issue by jplew** [ilearnio/module-alias#58]
Hi:
VS Code path resolution and auto-completion work great with all my project files that have been explicitly "included", but fail for any files that have been excluded. 

The relevant bits of my tsconfig.json:

```
{
  "compilerOptions": {
    "paths": {
      "~/*": ["./*"]
    }
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "src/__test__/**/*"
  ]
}
```

In my case, I want path aliasing functionality in my test files, but I don't want my tests transpiled and output to my `outDir`. 

Is it possible to take advantage of module aliases in a file, while simultaneously excluding it from transpilation?

Screenshot for reference:

![image](https://user-images.githubusercontent.com/462836/57247611-27fbe100-6ff5-11e9-9be2-e3fb1292474f.png)

**Comment by Kehrlann** [comment]
Hi @jplew,

If I understand correctly, you're using only the typescript compiler for path aliasing as of today. So you are not using module-alias yet, correct ?
If I understand correctly so far: as your typescript config does not work with excluded file, you would like to use module-alias instead, to have path resolution working. That might not be the best thing, please check the discussion on #19 

Let me know if it helps.

**Comment by jplew** [comment]
sorry if I was unclear. I already have module-alias installed and running in the above example. 

The library works fine for all the files in my `src` directory, but VS Code fails to autocomplete or recognize the aliases in my `src/__test__` directory.

**Comment by Kehrlann** [comment]
I see you've found an answer in #19 :+1:  It's not something we plan to address anytime soon - I'll close this issue.
