### ISSUE TITLE
[WHY] moduleAlias(__dirname + '/package.json')

### ISSUE THREAD

**Issue by iMegaMaximus2** [ilearnio/module-alias#60]
![image](https://user-images.githubusercontent.com/49617181/58228872-b2a04800-7d38-11e9-8301-6e4243e4413e.png)

The working nodejs directory is "build/server" and the file "package.json" (green) is present, but the system still uses the file in the root of the project "package.json" (red)

why this is not default option?
`moduleAlias(__dirname + '/package.json')`

**Comment by Kehrlann** [comment]
Interesting. I think it's because the default option is ../../package.json (up two levels from node_modules). We also have a process.cwd() default. Maybe process.cwd() should come first ? This would surely solve this gentleman's problem. 

I'd be inclined to do that. Any thoughts @ilearnio ?

**Comment by Kehrlann** [comment]
By the way @iMegaMaximus2 , what's the directory you're running your code from ? `Callbot/build/server` ?

It that's the case, to make module-alias work, instead of doing `require('module-alias/register');`, try `require('module-alias')({ base: process.cwd() });`, it should work. Let me know.

**Comment by ilearnio** [comment]
@Kehrlann I guess changing that will be a big breaking change. So for a lot of existing projects it may break the setup. I'd rather leave it as is, anyway the path to package.json is easy to customize and it suggeats the path well for most setups

**Comment by Kehrlann** [comment]
:+1: agreed, closing this.
