### ISSUE TITLE
Mocha compatibility 

### ISSUE THREAD

**Issue by liampmccabe** [ilearnio/module-alias#7]
Love this little package :) 

Any ideas how I can make it compatible with mocha?

Perhaps by editing mocha's loadFiles method?

```
/**
 * Load registered files.
 *
 * @api private
 */
Mocha.prototype.loadFiles = function (fn) {
  var self = this;
  var suite = this.suite;
  this.files.forEach(function (file) {
    file = path.resolve(file);
    suite.emit('pre-require', global, file, self);
    suite.emit('require', require(file), file, self);
    suite.emit('post-require', global, file, self);
  });
  fn && fn();
};
```

**Comment by ilearnio** [comment]
Hey @liampmccabe I just added a [test case](https://github.com/ilearnio/module-alias/commit/998a3b260c31eeccdb2024d4b1357185851b599b) that proves that module-alias is properly working inside of mocha environment. Maybe you are doing something wrong?

**Comment by ilearnio** [comment]
closing...

**Comment by ndabAP** [comment]
Not sure if the module is the problem but now I also get an error:

https://github.com/npm/lifecycle/issues/6

**Comment by ilearnio** [comment]
@ndabAP What is the error exactly? I can see only stack trace

**Comment by ndabAP** [comment]
I imported the wrong `app.js`. Sorry!
