### ISSUE TITLE
Strange?! Can't I alias "pull-fetch" module using "import" but other modules work just fine.

### ISSUE THREAD

**Issue by ruifortes** [ilearnio/module-alias#78]
Hi.
I can alias other modules with es6 import either using "node --experimental-modules ..." or "node -r esm ..." but not [pull-fetch](https://github.com/pull-stream/pull-fetch)'
Weird?! 
I'm not familiar with node internals so I couldn't event set a proper breakpoint to find where the problem is.
Does anyone knows why?
Thanks

**Comment by Kehrlann** [comment]
Hello Rui !

I thought es6 imports were not compatible with this library, see #59. Maybe I'm wrong and it now works ? 🤷

I am not sure what you're trying to achieve, or what your setup looks like. Could you please provide a minimal repo showing an alias that works and one that doesn't ?

**Comment by ruifortes** [comment]
Nevermind...
I'm using pnpm workspaces and its smartness ended up linking them together :\
Sorry, false alarm

**Comment by Kehrlann** [comment]
No worries ! Closing this, then 🙂
