### ISSUE TITLE
should be listed in the project's dependencies, not devDependencies

### ISSUE THREAD

**Issue by viT-1** [ilearnio/module-alias#79]
Using module-alias for jest.config.js which used another config files.
It should be devDependencies, but eslint with
```
'extends': [
	'eslint:recommended',
	'plugin:@typescript-eslint/recommended',
	'airbnb-typescript/base',
	'plugin:jest/all', // rules for .spec. files
	'plugin:jest-formatting/strict',
],
```
give me error:
`1:1   error    'module-alias' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies`

**Comment by Kehrlann** [comment]
Hi there !

Interesting, it means your eslint thinks your jest.config.js is a "project" file ... You can configure eslint to avoid applying this rule to your config file.

```
"import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/*.test.js", "**/*.spec.js", "jest.config.js"]}]
```

Source: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

**Comment by viT-1** [comment]
I use many configs such as tsconfig.js for dev/test/etc purposes, *.jest.config.js for various types of testind. Thats why these configs are not in root folder, may be it is a cause...

**Comment by viT-1** [comment]
@Kehrlann Thank you for workaround.
```
'rules':
'import/no-extraneous-dependencies': [
	'error', { 'devDependencies': ['**/*.spec.ts', '**/*.jest.config.js'] },
],
```
