### ISSUE TITLE
Error: [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by pwrnrd** [ilearnio/module-alias#80]
I get the following when trying to run my application:

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at init (D:\node_modules\module-alias\index.js:195:33)
    at Object.<anonymous> (D:\node_modules\module-alias\register.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

I tried:
- reinstalling module-alias
- installing an older version of module-alias (2.1)

Unfortunately these actions did not help.

Uninstalling module-alias did help, but ofcourse I received the error that the paths couldn't be resolved.

What would be the solution to this error?

**Comment by Kehrlann** [comment]
Hello !

Is this a new problem in a codebase that used to work with module-alias (that's why you would reinstall an older version of module-alias) ? Or is this a new usage of module-alias and it just doesn work ?

Could please share the piece of code where you import `module-alias/register` ?

**Comment by pwrnrd** [comment]
> Is this a new problem in a codebase that used to work with module-alias (that's why you would reinstall an older version of module-alias) ? Or is this a new usage of module-alias and it just doesn work ?

The code base used to work with module-alias. Unfortunately I can't pinpoint the exact change that has led to this issue, as my typescript project is still able to build and all my test seem to work. However, when I start the server this error appears.

> Could please share the piece of code where you import module-alias/register ?

In my main index file at line 1:

`import 'module-alias/register';`

**Comment by Kehrlann** [comment]
No idea why this is happening, so I have random questions:
- You compile you project with tsc and then run it with node, correct ? Not ts-node ?
- Could you share your package.json, at least the _moduleAlias / _moduleDirectories part ?
- Have you updated your node version recently ?

**Comment by pwrnrd** [comment]
> You compile you project with tsc and then run it with node, correct ? Not ts-node ?

Correct: Node.

> Could you share your package.json, at least the _moduleAlias / _moduleDirectories part ?

`
  "_moduleAliases": {
     "@orders": [
         "dist/bounded-contexts/orders"
      ],
      "@product-catalogue": [
         "dist/bounded-contexts/product-catalogue"
    ],
		"@account": [
			"dist/bounded-contexts/account/*"
		],
		"@shared": [
			"dist/shared-kernel"
		],
		"@": "dist"
	}
`

module alias version: 2.2.2

> Have you updated your node version recently ?

No I haven't.

**Comment by pwrnrd** [comment]
Addition: If I run the code using Node, I get the following error before the TypeError mentioned above:
```
  internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
```

**Comment by pwrnrd** [comment]
I dove into the pakcage and found the issue. As you can see in my package.json I put my paths in an array. Arrays are object, not strings. Hence, the error. So, simple fix: don't enclose the paths in an array. 

Although the fix is simple, for TypeScript users this is not really convenient to have tsconfig.json support arrays, while package.json only supports strings. What would be nice is if we could also support arrays in package.json.

```
		aliases[alias] = Array.isArray(aliases[alias]) 
			? nodePath.join(base, ...aliases[alias])
			: nodePath.join(base, aliases[alias])
```

I'll make a PR.

**Comment by Kehrlann** [comment]
Ah, good catch ! :clap:

**Comment by chikamichi** [comment]
Good catch. Btw tsconfig has this notion of fallbacks, hence the array support. I guess it wouldn't make much sense for module-alias right now.
