### ISSUE TITLE
module-alias doesn't work with jest

### ISSUE THREAD

**Issue by BlackoutGG** [ilearnio/module-alias#97]
Use case: I'm trying to test endpoints with jest and super test against an express api backend. My problem being I'm using module-alias to make my requires() a little more sane. Works fine when running it normally, however seen as I throw jest into the mix that's where everything goes pear shaped. From what I read module-alias doesn't work inside dependencies, so I guess it won't resolve within a test being executed by jest.

Here's the error I get:
` Test suite failed to run

    Cannot find module '@services' from 'users.unit.test.js'

       7 | });
       8 | 
    >  9 | console.log(require("@services"));`

Outside of tests everything works fine.

**Comment by Kehrlann** [comment]
Hi @BlackoutGG !

Yes that's a know issue ; `jest` completely overrides the normal import behavior, so module-alias can't do much. However jest has it's own way of defining aliases. That's documented in our [README](https://github.com/ilearnio/module-alias/blob/dev/README.md#Usage-with-jest) ; we point to [Jest docs](https://jestjs.io/docs/en/configuration#modulenamemapper-objectstring-string--arraystring) . I'm afraid  you'll have to copy your aliases over into you Jest confing.

Technically you could use a `config.js` file that would dynamically read your module-alias config from `package.json`, but unless you maintain a bajillion aliases that's probably not worth it.

Will close the issue.

PS: Your issue made me realize our link was out of date, thanks ^^
